// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9HrRL1I5OAn6Yk48CPT2hqHLpd51lWYc',
    appId: '1:998814947380:android:43eb8fcab4b57f84e35261',
    messagingSenderId: '998814947380',
    projectId: 'testingrxdart-course',
    storageBucket: 'testingrxdart-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKuUFaa7fKwfKwtQWHM8SX1i7N8-8fj1k',
    appId: '1:998814947380:ios:811511d2632eb234e35261',
    messagingSenderId: '998814947380',
    projectId: 'testingrxdart-course',
    storageBucket: 'testingrxdart-course.appspot.com',
    iosClientId: '998814947380-qvpj2d1b4pusn7nvl93qt9s6l7sl7se5.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.testingrxdartCourse',
  );
}
